default:
  default_args:
    start_date: "2025-05-21"

add_your_dag_name_here_df_dag:
  default_args:
    owner: "test_owner"
  description: "add your description here"
  tags:
    - "dag_factory"
  catchup: false
  schedule_interval: "0 0 * * *"
  tasks:
    bash_demo:
      operator: airflow.operators.bash.BashOperator
      bash_command: "echo hello world"
