name: Aggregate & Update DAGs

on:
  repository_dispatch:
    types: [ dag-updated ]
  workflow_dispatch:

concurrency:
  group: update-dags
  cancel-in-progress: true

jobs:
  update_dags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout umbrella + submodules (sparse)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
          token: ${{ secrets.SUBMODULE_PAT }}
          sparse-checkout: |
            dags
          sparse-checkout-cone-mode: true

      - name: Gather DAGs
        run: |
          rm -rf old_dags && mv dags old_dags || true
          rm -rf tmp dags
          mkdir -p tmp
          git submodule foreach --recursive '
            echo "Processing $name ($path)..."
            if [ -d "$toplevel/$path/dags" ]; then
              mkdir -p "$toplevel/tmp/$name"
              cp -r "$toplevel/$path/dags/." "$toplevel/tmp/$name/"
              echo "Copied DAGs from $name:"
              ls -la "$toplevel/$path/dags"
            else
              echo "No dags/ directory found in $name"
            fi
          '
          mv tmp dags

      - name: Commit updated DAGs
        run: |
          mkdir -p /tmp/repo
          cd /tmp/repo
          git clone https://x-access-token:${{ secrets.CDR_PUSH_PAT }}@github.com/bcdev/airflow-dags.git .

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          rm -rf dags/
          cp -r $GITHUB_WORKSPACE/dags ./dags
          
          git add dags
          if ! git diff --cached --quiet; then
            git commit -m "Update DAGs from submodules"
            git push origin HEAD:main
          else
            echo "No changes detected in dags folder"
          fi
