name: Update Submodules on Dispatch

on:
  repository_dispatch:
    types: [ dag-updated ]
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    permissions:
      contents: write


    steps:
      - name: Checkout umbrella + submodules (sparse)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
          token: ${{ secrets.SUBMODULE_PAT }}

      - name: Update submodules to latest main
        run: |
          git submodule foreach '
            echo "Updating $name ..."
            git checkout main || echo "$name has no main branch"
            git pull origin main || echo "$name pull failed"
          '

      - name: Commit and push if submodules changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: update submodules to latest main"

            git push "https://x-access-token:${{ secrets.SUBMODULE_PAT }}@github.com/bcdev/airflow-dags.git" HEAD:main
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.SUBMODULE_PAT }}
